# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Message.proto',
  package='wenlipackage',
  serialized_pb=_b('\n\rMessage.proto\x12\x0cwenlipackage\"F\n\tWSMessage\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x02(\t\x12\x0e\n\x06sender\x18\x03 \x02(\t\x12\x0c\n\x04time\x18\x04 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WSMESSAGE = _descriptor.Descriptor(
  name='WSMessage',
  full_name='wenlipackage.WSMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='wenlipackage.WSMessage.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='wenlipackage.WSMessage.content', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sender', full_name='wenlipackage.WSMessage.sender', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='wenlipackage.WSMessage.time', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['WSMessage'] = _WSMESSAGE

WSMessage = _reflection.GeneratedProtocolMessageType('WSMessage', (_message.Message,), dict(
  DESCRIPTOR = _WSMESSAGE,
  __module__ = 'Message_pb2'
  # @@protoc_insertion_point(class_scope:wenlipackage.WSMessage)
  ))
_sym_db.RegisterMessage(WSMessage)


# @@protoc_insertion_point(module_scope)
